from pathlib import Path

ROOT_DIR = Path(__file__).parent
FILES_DIR = ROOT_DIR / 'files'
WINDOW_ICON_PATH = FILES_DIR / 'icone.png'

# Sizing
BIG_FONT_SIZE = 40
MEDIUM_FONT_SIZE = 24
SMALL_FONT_SIZE = 18
TEXT_MARGIN = 15
MINIMUM_WIDTH = 500

# Colors
PRIMARY_COLOR = '#e4e7eb33'
DARKER_PRIMARY_COLOR = '#5796f43a'
DARKEST_PRIMARY_COLOR = '#669ff51c'
